## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [95]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [96]:
a = np.zeros((5, ))
b = np.zeros((5, 1))
c = np.zeros((10, 2))
d = np.zeros((3, 6, 2))
e = np.zeros((4, 3, 2, 1))
print(a.shape, b.shape, c.shape, d.shape, e.shape)

(5,) (5, 1) (10, 2) (3, 6, 2) (4, 3, 2, 1)


Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [97]:
a = np.ones((5, ), dtype=int)
b = np.ones((5, 1), dtype=int)
c = np.ones((10, 2), dtype=int)
d = np.ones((3, 6, 2), dtype=int)
e = np.ones((4, 3, 2, 1), dtype=int)
print(a.dtype, b.dtype, c.dtype, d.dtype, e.dtype)

int64 int64 int64 int64 int64


Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [98]:
# 2
a = a.reshape((1, -1))
b = b.reshape((-1, 5))
c = c.reshape((5, 4))
d = d.reshape((18, 2))
e = e.reshape((4, 6))
print("2 компонента:")
print(a.shape, b.shape, c.shape, d.shape, e.shape)

# 3
a = a.reshape((1, 1, -1))
b = b.reshape((-1, 1, 5))
c = c.reshape((5, 2, 2))
d = d.reshape((9, 2, 2))
e = e.reshape((4, 3, 2))
print("3 компонента:")
print(a.shape, b.shape, c.shape, d.shape, e.shape)

# 4
a = a.reshape((1, -1, 5, 1))
b = b.reshape((-1, 5, 1, 1))
c = c.reshape((5, 2, 2, -1))
d = d.reshape((3, 3, 2, 2))
e = e.reshape((2, -1, 3, 2))
print("4 компонента:")
print(a.shape, b.shape, c.shape, d.shape, e.shape)

2 компонента:
(1, 5) (1, 5) (5, 4) (18, 2) (4, 6)
3 компонента:
(1, 1, 5) (1, 1, 5) (5, 2, 2) (9, 2, 2) (4, 3, 2)
4 компонента:
(1, 1, 5, 1) (1, 5, 1, 1) (5, 2, 2, 1) (3, 3, 2, 2) (2, 2, 3, 2)


Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [99]:
v = np.random.randint(0, 9, size=(5, 7))

In [100]:
max_axis_1 = v.max(axis=1)
max_axis_0 = v.max(axis=0)
overall_sum = v.sum()
mean_axis_0 = v.mean(axis=0)
median_axis_1 = np.median(v, axis=1)
print(v)
print(max_axis_0, max_axis_1, overall_sum, mean_axis_0, median_axis_1, sep='\n')

[[2 0 1 1 5 5 2]
 [1 1 5 3 8 1 4]
 [0 7 5 5 3 5 5]
 [3 6 1 8 4 2 4]
 [0 6 0 8 8 4 8]]
[3 7 5 8 8 5 8]
[5 8 7 8 8]
131
[1.2 4.  2.4 5.  5.6 3.4 4.6]
[2. 3. 5. 4. 6.]


Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [101]:
print(v.shape)
print(v.shape[0])
print(v.shape[1])

(5, 7)
5
7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [102]:
print(v[v > 5])
print(v[v < 7][::-1])
print(v[np.logical_and(v > 3,  v % 4 == 0)])
print(v[v % 5 == 3])
max_v = v.max()
min_v = v.min()
print(np.argwhere(v == max_v))
print(np.argwhere(v == min_v))
print(np.argsort(v))

[8 7 6 8 6 8 8 8]
[4 0 6 0 4 2 4 1 6 3 5 5 3 5 5 0 4 1 3 5 1 1 2 5 5 1 1 0 2]
[8 4 8 4 4 8 8 4 8]
[3 8 3 3 8 8 8 8]
[[1 4]
 [3 3]
 [4 3]
 [4 4]
 [4 6]]
[[0 1]
 [2 0]
 [4 0]
 [4 2]]
[[1 2 3 0 6 4 5]
 [0 1 5 3 6 2 4]
 [0 4 2 3 5 6 1]
 [2 5 0 4 6 1 3]
 [0 2 5 1 3 4 6]]


Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [103]:
print(v * 3)
print(v / 7)
print(v ** (2 / 3))
print(np.sin(v))
print(np.log(v))

[[ 6  0  3  3 15 15  6]
 [ 3  3 15  9 24  3 12]
 [ 0 21 15 15  9 15 15]
 [ 9 18  3 24 12  6 12]
 [ 0 18  0 24 24 12 24]]
[[0.28571429 0.         0.14285714 0.14285714 0.71428571 0.71428571
  0.28571429]
 [0.14285714 0.14285714 0.71428571 0.42857143 1.14285714 0.14285714
  0.57142857]
 [0.         1.         0.71428571 0.71428571 0.42857143 0.71428571
  0.71428571]
 [0.42857143 0.85714286 0.14285714 1.14285714 0.57142857 0.28571429
  0.57142857]
 [0.         0.85714286 0.         1.14285714 1.14285714 0.57142857
  1.14285714]]
[[1.58740105 0.         1.         1.         2.92401774 2.92401774
  1.58740105]
 [1.         1.         2.92401774 2.08008382 4.         1.
  2.5198421 ]
 [0.         3.65930571 2.92401774 2.92401774 2.08008382 2.92401774
  2.92401774]
 [2.08008382 3.30192725 1.         4.         2.5198421  1.58740105
  2.5198421 ]
 [0.         3.30192725 0.         4.         4.         2.5198421
  4.        ]]
[[ 0.90929743  0.          0.84147098  0.84147098 -0.95892427 -0.9

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log
  """


### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [104]:
np.arange(1, 9 * 2, 2).reshape((3, 3))

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [105]:
np.arange(16 * 2, 1, -2).reshape((4, 4))

array([[32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10],
       [ 8,  6,  4,  2]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [106]:
v1 = np.linspace(-0.5, 0.5, 11)
v2 = np.linspace(-0.5, 0.5, 11)
coords = np.array(np.meshgrid(v1, v2, indexing="xy")).transpose(1, 2, 0)
print(coords)

[[[-0.5 -0.5]
  [-0.4 -0.5]
  [-0.3 -0.5]
  [-0.2 -0.5]
  [-0.1 -0.5]
  [ 0.  -0.5]
  [ 0.1 -0.5]
  [ 0.2 -0.5]
  [ 0.3 -0.5]
  [ 0.4 -0.5]
  [ 0.5 -0.5]]

 [[-0.5 -0.4]
  [-0.4 -0.4]
  [-0.3 -0.4]
  [-0.2 -0.4]
  [-0.1 -0.4]
  [ 0.  -0.4]
  [ 0.1 -0.4]
  [ 0.2 -0.4]
  [ 0.3 -0.4]
  [ 0.4 -0.4]
  [ 0.5 -0.4]]

 [[-0.5 -0.3]
  [-0.4 -0.3]
  [-0.3 -0.3]
  [-0.2 -0.3]
  [-0.1 -0.3]
  [ 0.  -0.3]
  [ 0.1 -0.3]
  [ 0.2 -0.3]
  [ 0.3 -0.3]
  [ 0.4 -0.3]
  [ 0.5 -0.3]]

 [[-0.5 -0.2]
  [-0.4 -0.2]
  [-0.3 -0.2]
  [-0.2 -0.2]
  [-0.1 -0.2]
  [ 0.  -0.2]
  [ 0.1 -0.2]
  [ 0.2 -0.2]
  [ 0.3 -0.2]
  [ 0.4 -0.2]
  [ 0.5 -0.2]]

 [[-0.5 -0.1]
  [-0.4 -0.1]
  [-0.3 -0.1]
  [-0.2 -0.1]
  [-0.1 -0.1]
  [ 0.  -0.1]
  [ 0.1 -0.1]
  [ 0.2 -0.1]
  [ 0.3 -0.1]
  [ 0.4 -0.1]
  [ 0.5 -0.1]]

 [[-0.5  0. ]
  [-0.4  0. ]
  [-0.3  0. ]
  [-0.2  0. ]
  [-0.1  0. ]
  [ 0.   0. ]
  [ 0.1  0. ]
  [ 0.2  0. ]
  [ 0.3  0. ]
  [ 0.4  0. ]
  [ 0.5  0. ]]

 [[-0.5  0.1]
  [-0.4  0.1]
  [-0.3  0.1]
  [-0.2  0.1]
  [-0.1 

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [107]:
def checkmate(x, y):
    return 1 - (x + y) % 2


np.fromfunction(checkmate, (8, 8), dtype=int)

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [108]:
def checkmate(x, y):
    return (x + y) % 2


np.fromfunction(checkmate, (8, 8), dtype=int)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [109]:
def lower_triangle(n):
    return np.tril(np.ones((n, n)))

lower_triangle(5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [110]:
def upper_triangle(n):
    return np.triu(np.ones((n, n)))

upper_triangle(5)

array([[1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.]])

Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [111]:
np.eye(10)[::-1]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [112]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [113]:
def expected_value_np(x):
    return x.mean()

In [114]:
def dispersion_np(x):
    return x.std() ** 2

In [115]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [116]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [117]:
def mean_square_difference_np(y1, y2):
    return np.mean((y1 - y2) ** 2)

In [118]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [119]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [120]:
def mean_abs_difference_np(y1, y2):
    return np.mean(np.abs(y1 - y2))

In [121]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [122]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [123]:
def matching_proba_np(y1, y2):
    return np.mean(y1 == y2)

In [124]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [125]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [126]:
def find_thresholds_np(y1, y2):
    length = len(y1)
    matching_zeros = np.logical_and(y1 == 0, y2 == 0)
    matching_ones = np.logical_and(y1 == 1, y2 == 1)

    # I can't believe they call it CUMSUM
    reported_zeros = np.cumsum(matching_zeros) / np.arange(1, length + 1)
    reported_zeros = np.insert(reported_zeros, 0, 1)

    reported_ones = np.cumsum(matching_ones[::-1])[::-1] / np.arange(1, length + 1)[::-1]
    reported_ones = np.append(reported_ones, 1)

    res = np.logical_and(reported_zeros > 0.5, reported_ones > 0.5).nonzero()[0]
    return res

In [127]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [128]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))
helper = np.ones((3, 1))

data = np.mean(data, axis=(2, 3))
data = data @ helper

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [129]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

result = (m2 @ W2) @ (m2 @ W2).T @ m1 @ W1

assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [130]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ (ячейка находится в очереди на сжигание за ведьмовство)
magical_helper = np.ones((32, 3))
result = result @ magical_helper
result = result / result.max()

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()